using System.Collections.Generic;
using System.Windows.Data;

namespace Gouter;

internal class AlbumPlaylist : IPlaylist
{
    /// <summary>
    /// 自動生成フラグ
    /// </summary>
    bool IPlaylist.IsAutoGenerated { get; } = true;

    /// <summary>
    /// アルバム名
    /// </summary>
    public string Name { get; }

    /// <summary>
    /// アルバム詳細情報
    /// </summary>
    public AlbumInfo Album { get; }

    /// <summary>
    /// トラック一覧
    /// </summary>
    public ObservableList<TrackInfo> Tracks { get; }

    /// <summary>
    /// トラック一覧(実装)
    /// </summary>
    IList<TrackInfo> IPlaylist.Tracks => this.Tracks;

    public AlbumPlaylist(AlbumInfo albumInfo)
    {
        this.Album = albumInfo;
        this.Tracks = new ObservableList<TrackInfo>();

        this.Name = albumInfo.Name;

        BindingOperations.EnableCollectionSynchronization(this.Tracks, new object());
    }
}
